/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    customers: Customer;
    orders: Order;
    pages: Page;
    posts: Post;
    'press-mentions': PressMention;
    'newsletter-subscribers': NewsletterSubscriber;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'press-mentions': PressMentionsSelect<false> | PressMentionsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility description. Required.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer credit, if any.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL slug — lowercase, dashes, no spaces. e.g. "linen-shirt-sand".
   */
  slug: string;
  status: 'draft' | 'published' | 'archived';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in USD cents. e.g. 4500 = $45.00.
   */
  basePrice: number;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Each variant is a size+color combo with its own inventory and SKU.
   */
  variants?:
    | {
        size: string;
        color: string;
        sku: string;
        inventory: number;
        /**
         * Only set if this variant has a different price from basePrice (cents).
         */
        priceOverride?: number | null;
        /**
         * Optional: variant-specific images.
         */
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in "You may also like" on product pages.
   */
  relatedProducts?: (number | Product)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Set by the Stripe webhook after first purchase.
   */
  stripeCustomerId?: string | null;
  /**
   * Whether the customer opted into marketing emails.
   */
  marketingOptIn?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Generated on creation.
   */
  orderNumber: string;
  customer: number | Customer;
  status: 'pending' | 'paid' | 'fulfilled' | 'shipped' | 'delivered' | 'refunded' | 'cancelled';
  items: {
    product: number | Product;
    /**
     * Snapshot of the variant SKU purchased.
     */
    variantSku: string;
    /**
     * e.g. "Size M / Sand".
     */
    variantLabel: string;
    quantity: number;
    /**
     * Price snapshot to preserve the order ledger.
     */
    priceAtPurchaseCents: number;
    id?: string | null;
  }[];
  /**
   * Sum of items.
   */
  subtotalCents: number;
  shippingCents: number;
  taxCents: number;
  /**
   * subtotal + shipping + tax.
   */
  totalCents: number;
  shippingAddress: {
    name: string;
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    postalCode: string;
    country: string;
  };
  stripePaymentIntentId?: string | null;
  stripeCheckoutSessionId?: string | null;
  trackingNumber?: string | null;
  trackingUrl?: string | null;
  /**
   * Denormalized from customer for easy email lookup.
   */
  customerEmail: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use "home" for the homepage.
   */
  slug: string;
  status: 'draft' | 'published';
  blocks?:
    | (
        | {
            image: number | Media;
            heading: string;
            subheading?: string | null;
            ctaText?: string | null;
            ctaUrl?: string | null;
            overlayOpacity?: ('none' | 'light' | 'medium' | 'dark') | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-header';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            image: number | Media;
            imageSide?: ('left' | 'right') | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaText?: string | null;
            ctaUrl?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-text-split';
          }
        | {
            columns?: ('2' | '3' | '4') | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-grid';
          }
        | {
            heading?: string | null;
            /**
             * Select 2–6 products to feature.
             */
            products?: (number | Product)[] | null;
            layout?: ('grid' | 'carousel') | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-products';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            lightbox?: boolean | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'lookbook-gallery';
          }
        | {
            quote: string;
            attribution?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorial-quote';
          }
        | {
            heading?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'press-strip';
          }
        | {
            heading?: string | null;
            testimonials?:
              | {
                  quote: string;
                  author: string;
                  location?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial-slider';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq-accordion';
          }
        | {
            heading?: string | null;
            body?: string | null;
            buttonText?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter-signup';
          }
        | {
            heading?: string | null;
            body?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-form';
          }
        | {
            heading: string;
            body?: string | null;
            ctaText: string;
            ctaUrl: string;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-banner';
          }
        | {
            /**
             * YouTube, Vimeo, or direct MP4 URL.
             */
            url: string;
            caption?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'video-embed';
          }
        | {
            heading?: string | null;
            cards?:
              | {
                  /**
                   * e.g. "01"
                   */
                  number: string;
                  heading: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'numbered-card-slider';
          }
        | {
            type?: ('spacer' | 'divider') | null;
            size?: ('sm' | 'md' | 'lg') | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer-divider';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional sections appended after the main content.
   */
  blocks?:
    | (
        | {
            image: number | Media;
            heading: string;
            subheading?: string | null;
            ctaText?: string | null;
            ctaUrl?: string | null;
            overlayOpacity?: ('none' | 'light' | 'medium' | 'dark') | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-header';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text';
          }
        | {
            image: number | Media;
            imageSide?: ('left' | 'right') | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaText?: string | null;
            ctaUrl?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-text-split';
          }
        | {
            columns?: ('2' | '3' | '4') | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-grid';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            lightbox?: boolean | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'lookbook-gallery';
          }
        | {
            quote: string;
            attribution?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorial-quote';
          }
        | {
            heading?: string | null;
            testimonials?:
              | {
                  quote: string;
                  author: string;
                  location?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial-slider';
          }
        | {
            heading: string;
            body?: string | null;
            ctaText: string;
            ctaUrl: string;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-banner';
          }
        | {
            /**
             * YouTube, Vimeo, or direct MP4 URL.
             */
            url: string;
            caption?: string | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'video-embed';
          }
        | {
            type?: ('spacer' | 'divider') | null;
            size?: ('sm' | 'md' | 'lg') | null;
            /**
             * Optional ID for in-page links, e.g. "about-us".
             */
            anchor?: string | null;
            padding?: ('sm' | 'md' | 'lg') | null;
            background?: {
              type?: ('none' | 'color' | 'image') | null;
              /**
               * CSS color value, e.g. #f5f0eb
               */
              color?: string | null;
              image?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer-divider';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-mentions".
 */
export interface PressMention {
  id: number;
  publication: string;
  logo?: (number | null) | Media;
  quote?: string | null;
  url?: string | null;
  date?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  source: 'footer' | 'block' | 'checkout' | 'other';
  subscribedAt: string;
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject: string;
  message: string;
  submittedAt: string;
  resolved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'press-mentions';
        value: number | PressMention;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  description?: T;
  basePrice?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        size?: T;
        color?: T;
        sku?: T;
        inventory?: T;
        priceOverride?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  stripeCustomerId?: T;
  marketingOptIn?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        variantSku?: T;
        variantLabel?: T;
        quantity?: T;
        priceAtPurchaseCents?: T;
        id?: T;
      };
  subtotalCents?: T;
  shippingCents?: T;
  taxCents?: T;
  totalCents?: T;
  shippingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  stripePaymentIntentId?: T;
  stripeCheckoutSessionId?: T;
  trackingNumber?: T;
  trackingUrl?: T;
  customerEmail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  blocks?:
    | T
    | {
        'hero-header'?:
          | T
          | {
              image?: T;
              heading?: T;
              subheading?: T;
              ctaText?: T;
              ctaUrl?: T;
              overlayOpacity?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-text-split'?:
          | T
          | {
              image?: T;
              imageSide?: T;
              heading?: T;
              body?: T;
              ctaText?: T;
              ctaUrl?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-grid'?:
          | T
          | {
              columns?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-products'?:
          | T
          | {
              heading?: T;
              products?: T;
              layout?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'lookbook-gallery'?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              lightbox?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'editorial-quote'?:
          | T
          | {
              quote?: T;
              attribution?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'press-strip'?:
          | T
          | {
              heading?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'testimonial-slider'?:
          | T
          | {
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    location?: T;
                    id?: T;
                  };
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'faq-accordion'?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'newsletter-signup'?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonText?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'contact-form'?:
          | T
          | {
              heading?: T;
              body?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cta-banner'?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaText?: T;
              ctaUrl?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'video-embed'?:
          | T
          | {
              url?: T;
              caption?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'numbered-card-slider'?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    number?: T;
                    heading?: T;
                    body?: T;
                    id?: T;
                  };
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'spacer-divider'?:
          | T
          | {
              type?: T;
              size?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        'hero-header'?:
          | T
          | {
              image?: T;
              heading?: T;
              subheading?: T;
              ctaText?: T;
              ctaUrl?: T;
              overlayOpacity?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text'?:
          | T
          | {
              content?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-text-split'?:
          | T
          | {
              image?: T;
              imageSide?: T;
              heading?: T;
              body?: T;
              ctaText?: T;
              ctaUrl?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-grid'?:
          | T
          | {
              columns?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'lookbook-gallery'?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              lightbox?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'editorial-quote'?:
          | T
          | {
              quote?: T;
              attribution?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'testimonial-slider'?:
          | T
          | {
              heading?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    location?: T;
                    id?: T;
                  };
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cta-banner'?:
          | T
          | {
              heading?: T;
              body?: T;
              ctaText?: T;
              ctaUrl?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'video-embed'?:
          | T
          | {
              url?: T;
              caption?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'spacer-divider'?:
          | T
          | {
              type?: T;
              size?: T;
              anchor?: T;
              padding?: T;
              background?:
                | T
                | {
                    type?: T;
                    color?: T;
                    image?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-mentions_select".
 */
export interface PressMentionsSelect<T extends boolean = true> {
  publication?: T;
  logo?: T;
  quote?: T;
  url?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  subscribedAt?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  submittedAt?: T;
  resolved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        /**
         * e.g. /shop, /about, /journal
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  announcementBar?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  linkGroups?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'tiktok' | 'x' | 'facebook' | 'pinterest' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  newsletterBlurb?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  brandName: string;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  commerce?: {
    freeShippingThresholdCents?: number | null;
    flatShippingRateCents?: number | null;
    supportEmail?: string | null;
  };
  emptyCartCopy?: string | null;
  analytics?: {
    /**
     * GA4 Measurement ID (G-XXXX).
     */
    gaId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  linkGroups?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  newsletterBlurb?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  brandName?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  commerce?:
    | T
    | {
        freeShippingThresholdCents?: T;
        flatShippingRateCents?: T;
        supportEmail?: T;
      };
  emptyCartCopy?: T;
  analytics?:
    | T
    | {
        gaId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  anchor?: string | null;
  padding?: ('sm' | 'md' | 'lg') | null;
  background?: {
    type?: ('none' | 'color' | 'image') | null;
    color?: string | null;
    image?: { url?: string | null } | number | null;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rich-text';
}

export interface EditorialQuoteBlock {
  quote: string;
  attribution?: string | null;
  anchor?: string | null;
  padding?: ('sm' | 'md' | 'lg') | null;
  background?: {
    type?: ('none' | 'color' | 'image') | null;
    color?: string | null;
    image?: { url?: string | null } | number | null;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'editorial-quote';
}

export interface CTABannerBlock {
  heading: string;
  body?: string | null;
  ctaText: string;
  ctaUrl: string;
  anchor?: string | null;
  padding?: ('sm' | 'md' | 'lg') | null;
  background?: {
    type?: ('none' | 'color' | 'image') | null;
    color?: string | null;
    image?: { url?: string | null } | number | null;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta-banner';
}

export interface SpacerDividerBlock {
  type?: ('spacer' | 'divider') | null;
  size?: ('sm' | 'md' | 'lg') | null;
  anchor?: string | null;
  padding?: ('sm' | 'md' | 'lg') | null;
  background?: {
    type?: ('none' | 'color' | 'image') | null;
    color?: string | null;
    image?: { url?: string | null } | number | null;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer-divider';
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}